%% DEFAULT CONFIGURATIONS %%
%% @TODO READ CONFIGS FROM GUI %%

%% CORRESPONS TO P IN PAPER %%
global PATCH_SIZE;
PATCH_SIZE = 7;

%% CORRESPONDS TO K IN PAPER %%
global NUM_NEIGHEREST_NEIGHBORS;
NUM_NEIGHEREST_NEIGHBORS = 3;

%% BOOLEAN TRUE (APPLY OPTICAL FLOW) | FALSE ( DON'T )
global BOOL_OPTICAL_FLOW;
BOOL_OPTICAL_FLOW = false;

%%
%% INTEGER CORRESPONDS TO WHICH OPTICAL FLOW ALGORITHM TO USE
%% 0 : LUKAS & KANADE
%% 1 : HORN SCHUNK
%% 2 : LUKAS & KANADAE + DERIVATIVE OF GAUSSIAN
%% 3 : ??
%%
global INT_OPTICAL_FLOW_ALGORITHM;
INT_OPTICAL_FLOW_ALGORITHM = 0;

%% 